sudo: false
language: node_js
node_js:
- '9'
cache: npm
install:
- npm install
script:
- npm run lint
before_deploy:
- echo "Initializing deployment..."
deploy:
  provider: heroku
  api_key: HEROKU_API
  app: london-transport
  on: master
after_deploy:
- echo "Deployment complete"
